### ISSUE TITLE
brew install --HEAD julia fails

### ISSUE THREAD

**Issue by idontgetoutmuch** [staticfloat/homebrew-julia#147]
```
~/Dropbox/Private//CSS $ brew install --HEAD julia
==> Installing julia from staticfloat/homebrew-julia
==> Installing dependencies for julia: mpfr, libmpc, openssl, libgit2, staticfloat/julia
==> Installing julia dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-3.1.2-p11.mavericks.bottle.tar.gz
######################################################################################## 100.0%
==> Pouring mpfr-3.1.2-p11.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/3.1.2-p11: 24 files, 3.5M
==> Installing julia dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3.mavericks.bottle.tar.gz
######################################################################################## 100.0%
==> Pouring libmpc-1.0.3.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3: 10 files, 380K
==> Installing julia dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.mavericks.bottle.tar.gz
######################################################################################## 100.0%
==> Pouring openssl-1.0.2a-1.mavericks.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2a-1: 463 files,  18M
==> Installing julia dependency: libgit2
==> Downloading https://homebrew.bintray.com/bottles/libgit2-0.22.0.mavericks.bottle.tar.gz
######################################################################################## 100.0%
==> Pouring libgit2-0.22.0.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libgit2/0.22.0: 83 files, 1.5M
==> Installing julia dependency: staticfloat/julia/suite-sparse-julia
==> Downloading https://juliabottles.s3.amazonaws.com/suite-sparse-julia-4.4.3.mavericks.bottle
######################################################################################## 100.0%
==> Pouring suite-sparse-julia-4.4.3.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Conflicts with suite-sparse in homebrew-science.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/suite-sparse-julia/lib
    CPPFLAGS: -I/usr/local/opt/suite-sparse-julia/include

==> Summary
🍺  /usr/local/Cellar/suite-sparse-julia/4.4.3: 80 files, 3.7M
==> Installing julia
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Building with an alternative Fortran compiler
This is unsupported.
==> Cloning https://github.com/JuliaLang/julia.git
Updating /Library/Caches/Homebrew/julia--git
Cloning into '/private/tmp/julia20150321-31140-1aq8nme'...
done.
Cloning into '/private/tmp/julia20150321-31140-1aq8nme/deps/libmojibake'...
done.
Note: checking out '86447ad060d6f4edf01f2a64b9598dfeeb6e6f7d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Cloning into '/private/tmp/julia20150321-31140-1aq8nme/deps/openspecfun'...
done.
Note: checking out '381db9bc865e51de67be9dcaa1610a6f90029c72'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Cloning into '/private/tmp/julia20150321-31140-1aq8nme/deps/libuv'...
done.
Note: checking out 'abcbb0c22faa527c427e1ea6b55f073836b26f69'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Cloning into '/private/tmp/julia20150321-31140-1aq8nme/deps/openlibm'...
done.
Note: checking out '3ee2a6e6a9fc68cbf2ab00f830b9059215e40b06'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

==> Downloading https://gist.github.com/staticfloat/3806093/raw/cb34c7262b9130f0e9e07641a66fcca
######################################################################################## 100.0%
==> Patching
patching file deps/Makefile
Hunk #1 succeeded at 1480 (offset 826 lines).
==> Downloading https://double-conversion.googlecode.com/files/double-conversion-1.1.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/julia--doubleconversion-1.1.1.tar.gz
==> Downloading http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/dSFMT-src-2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/julia--dsfmt-2.2.tar.gz
==> make -C contrib -f repackage_system_suitesparse4.make prefix=/usr/local/Cellar/julia/HEAD U
==> make prefix=/usr/local/Cellar/julia/HEAD USE_BLAS64=0 FC=/usr/local/bin/gfortran LLVM_CONFI
==> make prefix=/usr/local/Cellar/julia/HEAD USE_BLAS64=0 FC=/usr/local/bin/gfortran LLVM_CONFI
    % (cmd_desc, proc.returncode))
OSError: Command /private/tmp/julia20...ia-env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
make[2]: *** [julia-env] Error 1
make[1]: *** [/private/tmp/julia20150321-31140-1aq8nme/deps/julia-env/bin/activate] Error 2
make: *** [doc/_build/html] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/staticfloat/homebrew-julia/issues
```

**Comment by staticfloat** [comment]
Hmmm, I can't reproduce on my machine.  Can you gist the output of `brew install -v --HEAD julia`?

**Comment by idontgetoutmuch** [comment]
https://gist.github.com/idontgetoutmuch/d7784180f3f13d2db51e

**Comment by staticfloat** [comment]
Looks like you've got python problems.  Where does your `python` come from?  The relevant error is:
```
Installing setuptools, pip...
  Complete output from command /private/tmp/julia20...ia-env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/julia20150321-43105-1txodqw/deps/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 10, in <module>
  File "/private/tmp/julia20150321-43105-1txodqw/deps/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/util.py", line 18, in <module>
  File "/private/tmp/julia20150321-43105-1txodqw/deps/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/distlib/version.py", line 14, in <module>
  File "/private/tmp/julia20150321-43105-1txodqw/deps/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
```

**Comment by StefanKarpinski** [comment]
If you're having python problems I feel bad for you son. I got 99 problems but a snake ain't one.

**Comment by idontgetoutmuch** [comment]
```
brew unlink python
brew install python
```
did the trick. Afaict it replaced 2.7.8 by 2.7.9.
