### ISSUE TITLE
Deprecated... things...

### ISSUE THREAD

**Issue by SplashDance** [staticfloat/homebrew-julia#245]
`@staticfloat` (does this qualify as an appropriate "ping"??)

Figured I should report this error I'm getting when running `brew update && brew upgrade` even though this tap is not "actively maintained.

Just letting you know.

-Steve

Note: I've received additional, similar warnings but I'm only posting the ones that explicitly mention reporting to the staticfloat/julia tap. 

```
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/arpack-julia.rb:19:in `<class:ArpackJulia>'
Please report this to the staticfloat/julia tap!

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/llvm37-julia.rb:149:in `<class:Llvm37Julia>'
Please report this to the staticfloat/julia tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/arpack-julia.rb:19:in `<class:ArpackJulia>'
Please report this to the staticfloat/julia tap!

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/llvm37-julia.rb:149:in `<class:Llvm37Julia>'
Please report this to the staticfloat/julia tap!

```

**Comment by kirk86** [comment]
I get the same issue as well and I'm not sure if I should remove everything and reinstall?

```
Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/arpack-julia.rb:19:in `<class:ArpackJulia>'
Please report this to the staticfloat/julia tap!

Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/staticfloat/homebrew-julia/llvm37-julia.rb:149:in `<class:Llvm37Julia>'
Please report this to the staticfloat/julia tap!
find $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :python' "{}" \;
/usr/local/Cellar/libmagic/5.32/.brew/libmagic.rb:  depends_on :python => :optional
/usr/local/Cellar/nlopt/2.4.2_2/.brew/nlopt.rb:  depends_on :python => "numpy" if build.with? "python"
/usr/local/Cellar/tbb/2018_U2/.brew/tbb.rb:  depends_on :python if MacOS.version <= :snow_leopard
/usr/local/Cellar/graphviz/2.40.1/.brew/graphviz.rb:    depends_on :python
find $(brew --cellar) -maxdepth 4 -mindepth 4 -regex '.*\.rb$' -exec grep -r 'depends_on :fortran' "{}" \;
/usr/local/Cellar/hdf5/1.10.1_2/.brew/hdf5.rb:  depends_on :fortran
/usr/local/Cellar/openblas-julia/0.2.20/.brew/openblas-julia.rb:  depends_on :fortran
```
